apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.service.name }}-config"
  namespace: "{{ .Values.namespace }}"
data:
  NODE_ENV: "{{ .Values.nodeapp.nodeEnv }}"
  PORT: "{{ .Values.nodeapp.port }}"
