namespace: development

host:
  name: solarinformatics.hopto.org

ingress:
  name: nginx-ingress-dev
  className: nginx

controller:
  ingressClass: nginx
  allowSnippetAnnotations: true

services:
  user:
    name: user-service
    HealthPath: /user-health
    Path: /user/(.*)
    port: 80
  inventory:
    name: inventory-service
    HealthPath: /inventory-health
    Path: /inventory/(.*)
    port: 80
  user3:
    name: user3-service
    HealthPath: /user3-health
    Path: /user3/(.*)
    port: 80
  user4:
    name: user4-service
    HealthPath: /user4-health
    Path: /user4/(.*)
    port: 80    