namespace: stage

image:
  repository: wasti87/exercise-5
  tag: stage

ContainerConfig:
  replicas: 2
  containerPort: 3000

service:
  name: "user3"  
  port: 80
  targetPort: 3000

nodeapp:
  nodeEnv: "stage"
  port: 3000

