apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.service.name }}-deployment"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ .Values.ContainerConfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.ContainerConfig.containerPort }}
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: "{{ .Values.service.name }}-config"
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: "{{ .Values.service.name }}-config"
              key: PORT
        - name: data-value
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.service.name }}-secret"
              key: data-value-key
