apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}-service"
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.service.name }}
  type: ClusterIP 
