apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user4-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SyedAhmed-Coder/k8s.git
    targetRevision: prod
    path: helm-charts/user4/helm-chart
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
