apiVersion: v2
name: user2
description: A Helm chart for deploying the user2 service
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - user2
  - service
  - helm
maintainers:
  - name: Syed Ahmed
    email: syed.ahmed@solarinformatics.com
sources:
  - https://github.com/your-repo/user2-service
