namespace: preprod

image:
  repository: wasti87/exercise-5
  tag: preprod

ContainerConfig:
  replicas: 3
  containerPort: 3000

service:
  name": "user2"
  port: 80
  targetPort: 3000  

# name: "user2"
nodeapp:
  nodeEnv: "preprod"
  port: 3000