apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user1-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SyedAhmed-Coder/k8s.git
    targetRevision: dev
    path: helm-charts/user1/helm-chart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
