apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.host.name }}
      http:
        paths:             
          - path: {{ .Values.services.user.Path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.user.name }}
                port:
                  number: {{ .Values.services.user.port }}
          - path: {{ .Values.services.user1.Path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.user1.name }}
                port:
                  number: {{ .Values.services.user1.port }}
          - path: {{ .Values.services.user3.Path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.user3.name }}
                port:
                  number: {{ .Values.services.user3.port }}                  