namespace: dev

image:
  repository: wasti87/exercise-5
  tag: dev

ContainerConfig:
  replicas: 2
  containerPort: 3000

service:
  name: "user3"  
  port: 80
  targetPort: 3000

nodeapp:
  nodeEnv: "dev"
  port: 3000

