namespace: prod

image:
  repository: wasti87/exercise-5
  tag: prod

containerconfig:
  replicas: 2
  containerPort: 3000

service:
  name: "user4"  
  port: 80
  targetPort: 3000

nodeapp:
  nodeEnv: "prod"
  port: 3000

